### ISSUE TITLE
this is a test

### ISSUE THREAD

**Issue by mturro** [mshanken/thebigsmokes#1]
don't mind this it is just a test of the trello and github integration

**Comment by mturro** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;BExTjXGC&#x2F;1-test-card-1"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Test card 1</a>

**Comment by szhukov86** [comment]
here comes another comment from yours truly...

**Comment by mturro** [comment]
this is another comment
